export enum LovCode {
    LEVEL='LEVEL',
    GENDER='GENDER',
    SCHOOLSYSTEM='SCHOOL_SYSTEM',
    STUDENTFILES='STUDENT_FILES',
    ASSIGNEMENT_TYPE='ASSIGNEMENT_TYPE',
    TEMPLATE_TYPE='TEMPLATE_TYPE',
    VARIABLE='VARIABLE',
    STUDENT_STATUS='STUDENT_STATUS',
    DISCOUNT_TYPES='DISCOUNT_TYPES',
    MARITAL_STATUS='MARITAL_STATUS',
    EMPLOYMENT_TYPE ='EMPLOYMENT_TYPE',
    ALIVE_STATUS='ALIVE_STATUS',
    EDUCATION_TYPE='EDUCATION_TYPE',
    EMPLOYEE_DESIGNATION='EMPLOYEE_DESIGNATION',
  }

  export enum DesignationCode {
    MANAGER='MANAGER',
    SENIOR_DEVELOPER='SENIOR_DEVELOPER'
  }